config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}

  root controller: :rooms, action: :index

  get 'rooms/:id', to: 'room_messages#new'

  resources :room_messages
  resources :rooms

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  post   'invite'   => 'accesses#invite'
  delete 'uninvite' => 'accesses#uninvite'

  mount ActionCable.server => '/cable'
  
end

app/models/access.rb
class Access < ApplicationRecord

  module LimitOfUsedRooms
    LIMIT_OF_ROOM_TO_USE = 100
  end

  belongs_to :user
  belongs_to :room

  validates :user_id, presence: true
  validates :room_id, presence: true

  def self.under_created_room_limit_by_user?(current_user)
    where(user_id:current_user.id).count <= Access::LimitOfUsedRooms::LIMIT_OF_ROOM_TO_USE
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :room_messages, dependent: :destroy, inverse_of: :room
  has_many :accesses, dependent: :destroy

  validates :name, presence: true
  validates :name, length: {minimum: 3, maximum: 30} 
  
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord

  belongs_to :user
  belongs_to :room, inverse_of: :room_messages

  validates :room_id, presence: true
  validates :message, presence: true
  validates :message, length: {minimum: 0, maximum: 10000}

  def self.message_filter(room_id)
  	all.where(room_id:room_id)
  end
  
end

app/models/user.rb
class User < ApplicationRecord

  module Role
    ADMIN = 'admin'.freeze
    USER = 'user'.freeze
    GUEST = 'guest'.freeze
    ALL = [ADMIN, USER, GUEST]
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :accesses, dependent: :destroy

  validates :username, uniqueness: true, presence: true
  validates_presence_of :role
  validates_inclusion_of :role, in: Role::ALL

end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController

  def invite
    @room = Room.find_by_id(access_params[:room_id])
    checked_permission_for_update = @room.accesses.where(user_id:current_user.id)
    if checked_permission_for_update.empty?
      redirection_for_rooms_path_with_flash(:alert, I18n.t('accesses.alerts.not_authorized'))
    else
      new_access = @room.accesses.new(user_id:access_params[:access_for_user_id])
      if new_access.save
        flash[:notice] = I18n.t("accesses.notices.permission_added #{new_access.user.username}")
        redirect_to room_path(@room.id)
      else
        redirection_for_rooms_path_with_flash(:alert, I18n.t('accesses.alerts.not_added'))
      end
    end
  end

  def uninvite
    access = Access.find_by(user_id:access_params[:access_for_user_id], room_id:access_params[:room_id])
    if access.present?
      if access.delete
        flash[:alert] = I18n.t("#{access.user.username}'s accesses.alerts.not_added")
        redirect_to room_path(access_params[:room_id])
      else
        flash[:alert] = I18n.t("accesses.alerts.permission_has_not_been_delete #{access.user.username}")
        redirect_to room_path(access_params[:room_id])
      end
    else
      flash[:alert] = I18n.t("accesses.alerts.permission_has_removed_already #{access.user.username}")
      redirect_to room_path(access_params[:room_id])
    end
  end


  def access_params
    params.require(:access_params).permit(:access_for_user_id,
                                          :room_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Modules::RedirectionSupport

  before_action :authenticate_user!

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about

  end

  def contact

  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
  	params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
  	params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end

end 

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController

  def new
    @room = Room.find(params[:id])
    @current_room_id = @room.id

    if access_for_the_current_room?
      @rooms = Room.all
      @room_message = RoomMessage.message_filter(@room.id).order(created_at: :desc)
      @creator_of_message = User.all
      @new_room_message = RoomMessage.new
      @users = User.all
    else
      redirection_for_rooms_path_with_flash(:alert, I18n.t('room_messages.alerts.no_access'))
    end
  end

  def create
    @new_room_message = RoomMessage.new(message_params)
    @current_room_id = @new_room_message.room_id
    @new_room_message.save
    redirect_to room_path(@current_room_id)
  end

  private

  def message_params
    params.require(:room_message).permit(:message,:room_id,:user_id)
  end

  def access_for_the_current_room?
    Access.where(room_id:@current_room_id,user_id:current_user.id).empty? && @room.security == true ? false : true
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

	def index
		@rooms = Room.all
		@room = Room.new
	end

	def create
		if Access.under_created_room_limit_by_user?(current_user)
			@room = Room.new(room_params)
			if @room.save
				if is_the_room_secured?
					@access = @room.accesses.new(user_id:current_user.id)
					if @access.save
						redirection_for_rooms_path_with_flash(:notice, "Room has been created with name: #{@room.name}")
					else
						@room.delete
						redirection_for_rooms_path_with_flash(:alert, "Room hasn't been created")
					end
				else
					redirection_for_rooms_path_with_flash(:notice, "Room has been created with name: #{@room.name}")
				end
			else
				redirection_for_rooms_path_with_flash(:alert, "Room hasn't been created")
			end
		else
			redirection_for_rooms_path_with_flash(:alert, "Room hasn't been created, you are joined for to much rooms")
		end
	end

	def destroy
		@room = Room.find(params[:id])
		if @room.destroy
			redirection_for_rooms_path_with_flash(:alert, "#{@room.name}'s room has been closed")
		else
			redirection_to_a_room(@room.id, :alert, "Room with id: #{@room.id} has not been closed")
		end

	end

	private

	def room_params
		params.require(:room).permit(:name,
																 :security)
	end

	def is_the_room_secured?
		room_params['security'].to_i == 1
	end

end

app/helpers/accesses_helper.rb
module AccessesHelper

  def access_params_builder(user, current_room_id)
    {'access_params' => {:access_for_user_id => user.id, :room_id => current_room_id}}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_date(date)
    layout_format = date.strftime("%Y-%m-%d %H:%M")
    layout_format
  end

end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper

end

app/helpers/rooms_helper.rb
module RoomsHelper

  def is_user_inviteable?(user,current_room)
    current_room.accesses.where(user_id:user.id).empty? ? true : false
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private  Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br>
  <br>
      <div class="row">
        <div class="col-12">
          <%= render "shared/navbar" %>
          
             <% flash.each do |key, message| %>
               <div class="text-center alert alert-<%= key == 'notice' ? 'success' : 'danger' %>">
                 <%= message %> 
               </div>
             <% end %>

          <div class="container">  
          <%= yield %>
          </div>
      </div>
    </div>

    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/about.html.erb
<div id="content_of_about" class="row align-items-start">
   <div class="col-md-12"><h2>Rails based Chat-app</h2></div>
   <div class="col-md-12"><h3>Developed by Adam Nemeth © All rights reserved 2019</h3></div>
   <div class="col-md-12" style="margin-top: 150px;"><h4><%= link_to 'Contact with developer', contact_path %></h4></div>
</div>

app/views/pages/contact.html.erb
<div id="content_of_contact" class="row align-items-start">
   <div class="col-md-12"><h2>Rails based Chat-app</h2></div>
   <div class="col-md-12"><h3>If you have any question please contact with us</h3></div>
   <div class="col-md-12" style="margin-top: 150px;"><h4><a href="mailto:nemeth.richo@gmail.com?subject=about-chat-site">Email Us</a></h4></div>
</div>

app/views/room_messages/_form.html.erb
<%= form_for @new_room_message, remote: true do |form| %>
  <div id="input_field_for_message">
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text text-muted" >Message: </span>
        <%= form.text_field :message, id:'input_message', class: 'input_field_message'  %>
        <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
      </div>
    </div>
    <%= form.hidden_field :room_id, :value => @current_room_id %>
    <%= form.hidden_field :user_id, :value => current_user.id %>


<% end %>
</div>
</br>
</br>

<script>
    var input =  document.getElementById("input_message");
    input.focus();
    input.select();
</script>

app/views/room_messages/new.html.erb
<div id="list_of_room" class="col-md-5">
  <div class="small_content_holder">
    <h2>List of available rooms:</h2></br>
    <div style="margin-left: 2%;">
      <%= render 'rooms/rooms' %>
    </div>
    </br>
    <hr>

    <h2>List of Users:</h2></br>
    <div style="margin-left: 2%;">
      <%= render 'rooms/users' %>
    </div>
    </br>
  </div>
</div>

<div id="list_of_messages" class="col-md-7 align-items-center">
  <h2>You are in room: <%= @room.name %></h2>

  <div class="text-muted" style="margin-left:2%;padding-top:1%;">
    <h4>List of users in this room:</h4>
    <h4>Room's Id is: <%= @current_room_id %></h4></br>
  </div>

  <div class="small_content_holder_on_messages">
    <% @room_message.each do |message| %>
      <p><%= message.message %>
        <span class="text-muted">
          -
          <% @creator_of_message.each do |creator| %>
          <% if creator.id == message.user_id %>
          <%= creator.username %>
          -
          <%= format_date(message.created_at) %>
          <% end %>
          <% end %>
  	  </span>
      </p>
    <% end %>
  </div></br>

  <%= render 'form' %>

  </br>
  <hr>

  <div class="text-center">
    <%= link_to "Close the room", @room, method: :delete %></br>
    <%= link_to "Back for list of the rooms", rooms_path %>
  </div>
</div>

app/views/rooms/_form.html.erb
<%= form_for @room do |form| %>
  <div id="input_field_for_rooms">
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text text-muted">Name of Room: </span>
        <%= form.text_field :name, class: 'input_field_room'%></br></br>
        <span class="input-group-text text-muted">Would you like your room be secured?</span>
        <%= form.check_box :security %></br>
        <%= form.submit "Create", class: 'btn btn-primary btn-block text_for_form' %>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/_rooms.html.erb
<div class="small_content_holder_of_name_of_the_rooms">
<% unless @rooms.empty? %>
  <% @rooms.each do |room| %>
  	<h4><%= link_to room.name, room_path(room) %></h4>
  <% end %>
  <% else %>
    <h4>No Room</h4>
<% end %>
</div>

app/views/rooms/_users.html.erb
<div class="small_content_holder_of_name_of_the_rooms">
  <% unless @users.empty? %>
    <% @users.each do |user| %>
      <% unless user == current_user %>
        <h4><%= user.username%>
          <% if is_user_inviteable?(user, @room) %>
            <%= link_to 'Invite', invite_path(access_params_builder(user, @current_room_id)), class: "text-right", :method => :post %>
          <% else %>
            <%= link_to 'Uninvite', uninvite_path(access_params_builder(user, @current_room_id)), class: "text-right text-danger", :method => :delete %>
          <% end %>
        </h4>
      <% end %>
    <% end %>
  <% else %>
    <h4>No User</h4>
  <% end %>
</div>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render 'form' %>

app/views/rooms/index.html.erb
<div id="list_of_room" class="col-md-5">
  <div class="small_content_holder">
    <h2>List of available rooms:</h2></br>

    <div style="margin-left: 2%;">

      <%= render 'rooms' %>

    </div>

    </br>
    <hr>

    <h2 style="padding-top: 20px">Create a new Room</h2>

    </br>

    <%= render 'form' %>

    </br>

  </div>
</div>


<div id="list_of_messages" class="col-md-7 align-items-center">
  <div class="small_content_holder">
    <h2 class="">You are out of room</h2>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>
  Creating a room  
</h1>

<%= render 'form' %>

app/views/shared/_footer.html.erb
<br>
<br>
<div id="separator">
<hr>
</div>
<div class="container" style="margin-top: 35px">
        <p class="mt-2 text-center text-muted">
        	Chat App | Adam Nemeth © All rights reserved
        	<div class="links_in_the_footer"><p><%= link_to 'About Us', about_path, style: 'margin-right:20px' %><%= link_to 'Contact', contact_path %></p></div>
        </p>
</div>

app/views/shared/_navbar.html.erb
<header role="banner">
  <div>
    <nav id="nav_bar_for_links" role="navigation">
      <ul id="user_details_menu" class="nav navbar-nav navbar-right text-muted">
        <% if current_user %>
          <li class="nav-item" style="margin-left: 10px; margin-top: 10px"><h6>Username: <%= current_user.username %> - </h6></li>
          <li class="nav-item" style="margin-right: 10px; margin-top: 10px"><h6><%= link_to 'Logout', destroy_user_session_path, method: :delete %></h6></li>
        <% end %>
      </ul>
    </nav>
  </div>
  <br>
  <h1 class="mt-5 text-center"><%= link_to 'Private  Chat', root_path, style: "text-center" %></h1>

  <div id="separator">
    <hr>
  </div>

</header>